package AssignmenrGroovy
//6.Padded binary output Print the numbers from 0 to 15 in binary (use Java's Integer.toBinaryString() method). Use a method in String from the Groovy JDK to make all the output values have four digits.
println Integer.toBinaryString(0) 
println Integer.toBinaryString(1)
println Integer.toBinaryString(2)
println Integer.toBinaryString(3)
println Integer.toBinaryString(4)
println Integer.toBinaryString(5)
println Integer.toBinaryString(6)
println Integer.toBinaryString(7)
println Integer.toBinaryString(8)
println Integer.toBinaryString(9)
println Integer.toBinaryString(10)
println Integer.toBinaryString(11)
println Integer.toBinaryString(12)
println Integer.toBinaryString(13)
println Integer.toBinaryString(14)
println Integer.toBinaryString(15)